name: credit_hub_new
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: 
  device_preview:
  device_info_plus: 
  dio:
  dotted_border:
  equatable:
  flutter_bloc: 
  flutter_svg:
  flutter_dotenv: 
  freezed_annotation:
  font_awesome_flutter:
  fl_chart: 0.69.2
  get:
  gap:
  google_fonts: 5.0.0
  intl:
  image_picker: 
  json_annotation: 
  logger:
  retrofit:
  pinput:  
  shared_preferences:
  stylish_bottom_bar:
  calendar_date_picker2:
  # syncfusion_flutter_datepicker: 21.2.10
  # flutter_date_picker_timeline:


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 
  flutter_lints: ^2.0.0
  freezed:
  json_serializable: 
  retrofit_generator: 

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/auth/header_signin.png
    - assets/images/auth/coin_right_signin.png
    - assets/images/auth/footer_signin.png
    - assets/images/main/account.svg
    - assets/images/main/history.svg
    - assets/images/main/home.svg
    - assets/images/main/notification.svg
    - assets/images/main/filter.svg
    - assets/images/main/back.svg
    - assets/images/main/pos.png
    - assets/images/main/banner_dashboard.png
    - assets/images/main/banner_account.png
    - assets/images/main/money_acc.png
    - assets/images/main/money_add.png
    - assets/images/main/noti.png
    - assets/images/main/camera.png
    - assets/images/main/rubbish.png
    - assets/images/main/edit.png



fonts:
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/roboto/Roboto-Regular.ttf
    #     - asset: assets/fonts/roboto/Roboto-Medium.ttf
    #     - asset: assets/fonts/roboto/Roboto-Bold.ttf
    #     - asset: assets/fonts/roboto/Roboto-Black.ttf

    # - family: PublicSans
    #   fonts:
    #     - asset: assets/fonts/public_sans/PublicSans-Regular.ttf
    #     - asset: assets/fonts/public_sans/PublicSans-Medium.ttf
    #     - asset: assets/fonts/public_sans/PublicSans-Bold.ttf
    #     - asset: assets/fonts/public_sans/PublicSans-Bold.ttf
    #     - asset: assets/fonts/public_sans/PublicSans-Black.ttf

    # - family: Inter
    #   fonts:
    #     - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
    #     - asset: assets/fonts/inter/Inter_24pt-Regular.ttf
    #     - asset: assets/fonts/inter/Inter_28pt-Regular.ttf
    #     - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
    #     - asset: assets/fonts/inter/Inter_24pt-Medium.ttf
    #     - asset: assets/fonts/inter/Inter_28pt-Medium.ttf
    #     - asset: assets/fonts/inter/Inter_18pt-Italic.ttf
    #     - asset: assets/fonts/inter/Inter_24pt-Italic.ttf
    #     - asset: assets/fonts/inter/Inter_28pt-Italic.ttf
    #     - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
    #     - asset: assets/fonts/inter/Inter_24pt-Bold.ttf
    #     - asset: assets/fonts/inter/Inter_28pt-Bold.ttf
    #     - asset: assets/fonts/inter/Inter_18pt-Black.ttf
    #     - asset: assets/fonts/inter/Inter_24pt-Black.ttf
    #     - asset: assets/fonts/inter/Inter_28pt-Black.ttf

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/sf/SF-Pro-Display-Black.otf
