
analyzer:
  errors:
    unused_import: ignore
    prefer_const_constructors: ignore
    avoid_print: ignore
    unnecessary_brace_in_string_interps: ignore
    use_full_hex_values_for_flutter_colors: ignore
    constant_identifier_names: ignore
    file_names: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_interpolation_to_compose_strings: ignore
include: package:flutter_lints/flutter.yaml

linter:

  rules:
